### ISSUE TITLE
Optimize compute units via compiler flags

### ISSUE THREAD

**Issue by armaniferrante** [Bonfida/dex-v4#23]
The following Cargo.toml settings have been shown to reduce compute units

```toml
[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
```

Example here https://github.com/project-serum/serum-dex/pull/159
